ads/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='ads'
urlpatterns = [
    path('', views.AdListView.as_view()),
    path('ads', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),
    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),
    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),
]

mysite/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.static import serve

urlpatterns = [
    path('', include('home.urls')),  # Change to ads.urls
    path('admin/', admin.site.urls),  # Keep
    path('accounts/', include('django.contrib.auth.urls')),  # Keep
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # Keep

    # Sample applications
    #path('hello/', include('hello.urls')),
    path('signup/', include('signup.urls')),
    path('home/', include('home.urls')),
    #path('authz/', include('authz.urls')),
    #path('myarts/', include('myarts.urls')),
    #path('polls/', include('polls.urls')),
    #path('autos/', include('autos.urls')),
    #path('cats/', include('cats.urls')),
    #path('ads/', include('ads.urls')),
    path('menu/', include('menu.urls')),
    path('web_ideas/', include('web_ideas.urls')),
    path('bailfund/', include('bailfund.urls')),
    #path('unesco/', include('unesco.urls')),
]

# Serve the static HTML
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
urlpatterns += [
    url(r'^site/(?P<path>.*)$', serve,
        {'document_root': os.path.join(BASE_DIR, 'site'),
         'show_indexes': True},
        name='site_path'
        ),
]

# Serve the favicon - Keep for later
urlpatterns += [
    path('favicon.ico', serve, {
            'path': 'favicon.ico',
            'document_root': os.path.join(BASE_DIR, 'home/static'),
        }
    ),
]

# Switch to social login if it is configured - Keep for later
try:
    from . import github_settings
    social_login = 'registration/login_social.html'
    urlpatterns.insert(0,
                       path('accounts/login/', auth_views.LoginView.as_view(template_name=social_login))
                       )
    print('Using', social_login, 'as the login template')
except:
    print('Using registration/login.html as the login template')

# References

# https://docs.djangoproject.com/en/3.0/ref/urls/#include

web_ideas/urls.py
from django.urls import path, reverse_lazy

from . import views

app_name = 'web_ideas'
urlpatterns = [
    path('', views.IdeaListView.as_view()),
    path('web_ideas', views.IdeaListView.as_view(), name='all'),
    path('ideas/<int:pk>', views.IdeaDetailView.as_view(), name='ideas_detail'),
    path('ideas/create',
        views.IdeaCreateView.as_view(success_url=reverse_lazy('web_ideas:all')), name='ideas_create'),
    path('ideas/<int:pk>/update',
        views.IdeaUpdateView.as_view(success_url=reverse_lazy('web_ideas:all')), name='ideas_update'),
    path('ideas/<int:pk>/delete',
        views.IdeaDeleteView.as_view(success_url=reverse_lazy('web_ideas:all')), name='ideas_delete'),
]

web_ideas/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

class Priority(models.Model) :
    name = models.CharField(max_length=6,null=True)

    def __str__(self) :
        return self.name

class Difficulty(models.Model) :
    name = models.CharField(max_length=6,null=True)

    def __str__(self) :
        return self.name

class Status(models.Model) :
    name = models.CharField(max_length=12,null=True)

    def __str__(self) :
        return self.name




class Ideas(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )

    priority = models.ForeignKey(Priority, on_delete=models.SET_NULL,null=True)
    description = models.CharField(max_length=2000,null=True)
    difficulty = models.ForeignKey(Difficulty, on_delete=models.SET_NULL,null=True)
    status = models.ForeignKey(Status, on_delete=models.SET_NULL,null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    linkedin_url = models.CharField(max_length=500, blank=True)
    created_at = models.DateTimeField(auto_now_add=True,null=True)
    updated_at = models.DateTimeField(auto_now=True,null=True)

    def __str__(self):
        return self.nickname

web_ideas/views.py
from web_ideas.models import Priority,  Difficulty, Status, Ideas
from web_ideas.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView




class IdeaListView(OwnerListView):
    model = Ideas
    # By convention:
    # template_name = "ads/ad_list.html"


class IdeaDetailView(OwnerDetailView):
    model = Ideas


class IdeaCreateView(OwnerCreateView):
    model = Ideas
    fields = ['name', 'priority','difficulty', 'status','description','linkedin_url']


class IdeaUpdateView(OwnerUpdateView):
    model = Ideas
    fields = ['name', 'priority', 'difficulty','status','description','linkedin_url']


class IdeaDeleteView(OwnerDeleteView):
    model = Ideas

web_ideas/templates/web_ideas/ideas_confirm_delete.html
{% extends "home/base_menu.html" %}
{% block content %}
<h1>Delete Idea</h1>

<p>Are you sure you want to delete the Idea "{{ idea }}"?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

web_ideas/templates/web_ideas/ideas_detail.html
{% extends "home/base_menu.html" %}

{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block content %}
<span style="float: right;">
({{ ideas.updated_at|naturaltime }})
{% if ideas.owner == user %}
<a href="{% url 'web_ideas:ideas_update' ideas.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'web_ideas:ideas_delete' ideas.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ ideas.name }}</h1>
<p>
{{ ideas.priotity }}
</br>
</p>
<p>
Description: {{ideas.description}}
</p>
<p>
Difficulty: {{ideas.difficulty}}
</p>
<p>
Status: {{ideas.status}}
</p>
<p>
Owner: {{ideas.owner}}
</p>
<p>
Created: {{ideas.created_at}} UTC
</p>
<p>
Updated: {{ideas.updated_at}} UTC
</p>
<p>
Linked In Post: <a href="{{ideas.linkedin_url}}">Linked In Job</a>
</p>

<p>
<a href="{% url 'web_ideas:all' %}">All Ideas</a>
</p>
{% endblock %}

web_ideas/templates/web_ideas/ideas_form.html
{% extends "home/base_menu.html" %}

{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'web_ideas:all' %}';return false;">
  </form>
</p>
{% endblock %}

web_ideas/templates/web_ideas/ideas_list.html
{% extends "home/base_menu.html" %}
{% block content %}
<h1>Bart's Web Ideas</h1>
<p>
{% if ideas_list %}
<table>
    <tr>
        <th>Name    &nbsp;</th>
        <th>Priority    &nbsp;</th>
        <th>Difficulty    &nbsp;</th>
        <th>Status    &nbsp;</th>
        <th>Owner    &nbsp;</th>
        <th>Update  &nbsp;</th>
        <th>Delete  &nbsp;</th>
    </tr>
  {% for idea in ideas_list %}

    <tr>
        <td></th><a href="{% url 'web_ideas:ideas_detail'  idea.id %}">{{ idea.name }} &nbsp;</a></td>

        <td>{{idea.priority}} &nbsp;</td>
        <td>{{idea.difficulty}} &nbsp;</td>
        {% if idea.status|slugify == 'not-started' %}
        <td style="background-color:#ff6699;">
        {% elif idea.status|slugify  == 'completed' %}
        <td style="background-color:#66ff99;">
        {% elif idea.status|slugify  == 'in-progress' %}
        <td style="background-color:#ffff66;">
        {% else %}
        <td>
        {% endif %}
            {{idea.status}} &nbsp;</td>

        <td>{{idea.owner}} &nbsp;</td>
        {% if idea.owner == user or user.is_superuser %}
        <td>&nbsp;  <a href="{% url 'web_ideas:ideas_update' idea.id %}">Edit</a> </td>
        <td>&nbsp;  <a href="{% url 'web_ideas:ideas_delete' idea.id %}">Delete</a></td>
        {% endif %}
    </tr>
  {% endfor %}
</table>
{% else %}
  <p>There are no ideas in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'web_ideas:ideas_create' %}">Add Idea</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'web_ideas:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'web_ideas:all' %}">Login</a>
{% endif %}
</p>


{% endblock %}